Проект ShareIt. Техническое задание. Часть 1
KseniaYakovenko/java-shareit pull request #1
Opened 2024-07-12 15:31 UTC by KseniaYakovenko

2024-07-13 16:38 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-07-13 16:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/repository/InMemoryUserRepositoryImpl.java
> +    public void checkEmail(User user) {
При такой реализации проверки в худшем случае нам потребуется для проверки существования `email` `O(n)` времени, существует реализация при которой того же эффекта можно добиться за `O(1)` необходимо добавить еще один словарь, где ключами являются адреса электронной почты

2024-07-13 16:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/repository/InMemoryUserRepositoryImpl.java
> +        if (user == null) throw new NotFoundException("Нет пользователя с id = " + userId);
В соответствии с Java Google Code Style советую всегда использовать опциональные скобки:

https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used

2024-07-13 16:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    String email;
Необходимы модификаторы доступа

2024-07-13 16:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/dto/UserDtoMapper.java
> +public class UserDtoMapper {
Это класс-помощник стоит реализовать его в соответствии с этим:

https://www.baeldung.com/java-helper-vs-utility-classes

2024-07-13 16:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    String email;
Необходимо добавить модификаторы доступа

2024-07-13 16:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    LocalDateTime created;
Необходимо добавить модификаторы доступа

2024-07-13 16:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        } else {
Нет необходимости в `else`, так как ты делаешь `return` в предыдущей ветке условного оператора:

```java
if (query == null || query.isBlank()) {
    return Collections.emptyList();
}
return itemRepository.search(query).stream().map(ItemDtoMapper::toItemDto).collect(Collectors.toList());
```

2024-07-13 16:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +        if (item == null) throw new NotFoundException("Нет item с id = " + itemId);
Аналогично тому, что уже писал

2024-07-14 18:43 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/user/repository/InMemoryUserRepositoryImpl.java
> +        if (user == null) throw new NotFoundException("Нет пользователя с id = " + userId);
исправила

2024-07-14 18:46 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    String email;
добавила

2024-07-14 18:49 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    String email;
исправила

2024-07-14 18:49 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    LocalDateTime created;
добавила

2024-07-14 18:53 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +        if (item == null) throw new NotFoundException("Нет item с id = " + itemId);
исправила

2024-07-14 18:53 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        } else {
спасибо, исправила

2024-07-14 20:01 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/user/repository/InMemoryUserRepositoryImpl.java
> +    public void checkEmail(User user) {
исправила

2024-07-14 20:23 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/user/dto/UserDtoMapper.java
> +public class UserDtoMapper {
непонятно, в чем именно неправильно реализован, можешь уточнить

2024-07-14 20:24 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +        if (item == null) throw new NotFoundException("Нет item с id = " + itemId);
исправила

2024-07-15 13:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/dto/UserDtoMapper.java
> +public class UserDtoMapper {
Стоит добавить приватный конструктор без аргументов и самому классу добавить аннотацию `final`:

```java
public final class UserDtoMapper {
    private UserDtoMapper() {
    }
}
```

2024-07-15 13:39 UTC, LexLippi commented
Привет!

Написал, как необходимо переделать мапперы. 

Желаю удачи!

2024-07-15 15:16 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/user/dto/UserDtoMapper.java
> +public class UserDtoMapper {
Спасибо, исправила

2024-07-16 08:31 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-07-26 20:21 UTC, merged