sprint 14 ShareIt add bookings
KseniaYakovenko/java-shareit pull request #2
Opened 2024-07-29 01:20 UTC by KseniaYakovenko

Проект ShareIt. Техническое задание. Часть 2

2024-07-29 08:09 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторые замечания, которые необходимо исправить!

Желаю удачи!

2024-07-29 08:09 UTC, LexLippi commented on src/main/resources/schema.sql
> +    text          VARCHAR(1000)                           NOT NULL,
Когда название поля совпадает с названием типа данных, то лучше использовать кавычки \`\` для экранирования

2024-07-29 08:09 UTC, LexLippi commented on src/main/resources/schema.sql
> +    created_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
можно добавить значение по умолчанию `default now()`

2024-07-29 08:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>      }
Этот метод явно не должен называться `getBookings`, так как он не возвращает никакого результата

2024-07-29 08:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private static Consumer<ItemInfoDto> getItemInfoDtoConsumer(List<Booking> bookings) {
Пока не очень понятно зачем для этого однострочника нам понадобился отдельный метод

2024-07-29 08:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public List<ItemInfoDto> getUserItems(long userId) {
Этому методу необходима `readonly`-транзакция

2024-07-29 08:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>      public ItemDto update(ItemDto itemDto, long userId) {
Этому методу не хватает аннотации `@Transactional`

2024-07-29 08:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public ItemInfoDto getById(long itemId, long userId) {
Этому методу не хватает `readonly`-транзакции

2024-07-29 08:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/dto/ItemInfoDto.java
> +    List<CommentDto> comments;
Модификаторы доступа

2024-07-29 08:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/dto/CommentRequestDto.java
> +    String text;
Модификаторы доступа

2024-07-29 08:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    LocalDateTime created;
Модификаторы доступа

2024-07-29 08:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/exception/UnAvailableItemException.java
> +    public UnAvailableItemException(String message) {
`Unavailable`

2024-07-29 08:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        }
можно использовать тернарный оператор и избежать объявления переменной в отрыве от инициализации

2024-07-29 08:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    @Override
Не хватает аннотации `@Transactional(readOnly=true)`

2024-07-29 08:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public List<BookingDto> getBookingsForOwner(long ownerId, BookingState state) {
аналогично про аннотацию

2024-07-29 08:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/dto/BookingRequestDto.java
> +    Long bookerId;
Модификаторы доступа

2024-07-29 08:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    Long bookerId;
Модификаторы доступа

2024-07-29 08:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingStatus.java
> +        return null;
Лучше использовать `Stream API` и в случае отсутствия элемента возвращать либо пустой `Optional`, либо исключение

2024-07-29 08:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingState.java
> +    }
Аналогично тому, что писал уже

2024-07-29 09:25 UTC, KseniaYakovenko commented on src/main/resources/schema.sql
> +    text          VARCHAR(1000)                           NOT NULL,
спасибо, исправила название поля

2024-07-29 09:27 UTC, KseniaYakovenko commented on src/main/resources/schema.sql
> +    created_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
добавила

2024-07-29 09:29 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>      }
исправила

2024-07-29 09:30 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private static Consumer<ItemInfoDto> getItemInfoDtoConsumer(List<Booking> bookings) {
исправила

2024-07-29 09:33 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public List<ItemInfoDto> getUserItems(long userId) {
добавила

2024-07-29 09:34 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>      public ItemDto update(ItemDto itemDto, long userId) {
добавила

2024-07-29 09:35 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public ItemInfoDto getById(long itemId, long userId) {
добавила

2024-07-29 09:35 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/item/dto/ItemInfoDto.java
> +    List<CommentDto> comments;
добавила

2024-07-29 09:36 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/item/dto/CommentRequestDto.java
> +    String text;
добавила

2024-07-29 09:36 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    LocalDateTime created;
добавила

2024-07-29 09:38 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/exception/UnAvailableItemException.java
> +    public UnAvailableItemException(String message) {
исправила

2024-07-29 09:43 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        }
спасибо, исправила

2024-07-29 09:44 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    @Override
добавила

2024-07-29 09:45 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public List<BookingDto> getBookingsForOwner(long ownerId, BookingState state) {
добавила

2024-07-29 09:45 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/booking/dto/BookingRequestDto.java
> +    Long bookerId;
добавила

2024-07-29 09:45 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    Long bookerId;
добавила

2024-07-29 09:53 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/booking/BookingStatus.java
> +        return null;
исправила

2024-07-29 09:53 UTC, KseniaYakovenko commented on src/main/java/ru/practicum/shareit/booking/BookingState.java
> +    }
исправила

2024-07-30 08:09 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-08-08 17:32 UTC, merged